
name: test and build back

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
  DOCKER_USERNAME: nologin

jobs:
  build:
    runs-on: ubuntu-latest

    steps :
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

    - name: Checkout
      uses: actions/checkout@v3

    - name: Test with Maven
      run : mvn -B clean test --file pom.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        registry: rg.fr-par.scw.cloud/polytech2024
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_API_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: rg.fr-par.scw.cloud/polytech2024/juso/backend:v1